### ISSUE TITLE
Support latest Builder improvements

### ISSUE THREAD

**Issue by deldrid1** [NasibMansour/imp-central-impt#14]
Builder 2.6.0, 2.7.0, and 2.8.0 have been released since we started this project which each address a different issue that we have had with the tool.  We need to implement the following functionality in impt by including the latest Builder:

- Make sure that we are capturing all Builder log output and logging things like duplicate `@include` detection introduced in 2.6.0.
- For every build we need to save the file that Builder can create https://github.com/electricimp/Builder#reproducible-artifacts (perhaps put the imp deployment ID in the saved file?)
- Make sure we are using the --use-remote-relative-includes option by default

**Comment by NasibMansour** [comment]
Found bugs in Builder in the last point.
First two points are done.

**Comment by NasibMansour** [comment]
Closing this issue as the last point is working after fixing the bugs in the latest Builder release: [v2.8.1](https://github.com/electricimp/Builder/releases/tag/v2.8.1)
