### ISSUE TITLE
Add option to list info of all auth accounts in the settings file (default and not default)

### ISSUE THREAD

**Issue by NasibMansour** [NasibMansour/imp-central-impt#4]
Either `impt auth list` or preferably `impt auth info -l`

**Comment by deldrid1** [comment]
I think its just `impt auth info` right?

If you want to add some flags you could do 
- `impt auth info --account $UUID` to only show the info for a particular account 
- `impt auth info --default` to only show the default account

**Comment by NasibMansour** [comment]
Yes it is `impt auth info` I think the first point goes along with issue #3 ?
Also, I may understood it wrong? so we need `impt auth info` to list all and if we specify an account using a flag then list just that one?

**Comment by deldrid1** [comment]
Yes

Correct.
